package main

var jokes = []string{
	"Q: What happened to the pirate when his wooden leg caught fire?\nA: He got burnt to the ground.",
	"How did the pirate become a boxing champion so fast?\n - Nobody was ready to take on his right hook.",
	"What do you call a pirate with two eyes, two hands and two legs?\n - A beginner.",
	"What does the pirate say when he steps on a Lego?\n -Arrrrrgh!!!",
	"It always struck me as odd that the Pirates of the Caribbean DVD had a piracy warning…",
	"To err is human. To arr is seriously pirate.",
	"Why are pirates such eager readers of the Playboy?\n - Because of the arrrticles.",
	"Oh no, sir, I said pirate ship. What on Earth would possess me to call you a pile of shit?!",
	"How do pirates communicate with each other?\n -With an Aye phone.",
	"What is regularly given to the sea around 8 am, if the digestion is right?\n - The captain’s log.",
	"How do pirates know that they are pirates?\n - They think so, therefore they arrr.",
	"What is a pirate’s favorite movie?\n- Booty and the Beast. (But it is arr-rated.)",
	"Why don’t the Chinese make very good pirates?\n- Because they’re not very strong in the ‘Arrrr!’ department.",
	"How did Captain Hook died?\n- Multiple stabbings. He got a bad case of an itchy rash.",
	"What do you get when you cross a parrot and a shark?\n- A bird that will talk your head off.",
	"How did Capitan Hook die? \n- He got distracted and wiped his butt with the wrong hand.",
	"In case his ship is sunk, every pirate carries a bar of soap with him at all times. \n- You know, to wash him ashore.",
	"Who was the first pirate?\n- Noah, the builder of the Arrrrk.",
	"Steve: I know a pirate with a wooden leg called Joe.\n Pete: Really? I wonder what he called his hook.",
	"What’s the difference between a pirate and a strawberry farmer?\n The pirate buries his treasure, the farmer treasures his berries.",
	"Why did the pirate cross the road?\n To reach the second hand shop.",
	"What is pirates’ favorite choice of music?\n- aRR n’ B",
	"Why are pirates bad at cards?\n- It’s kind of hard to play when you’re sitting on the deck.",
	"How does a pirate get to the top of the building?\n- By elevataaaaarrrrrr!!!!!",
	"What kind of a ship is most feared by pirates?\nThe Steady Relationship.",
	"How does a pirate declutter his ship?\nBy having a yarrrrd sale.",
	"Why don’t you usually see a pirate that is a smoker?\nBecause they use the patch.",
	"A pirate has stopped his pirating and mended his ways, but his parrot was just too bad, constantly swearing and refusing to behave. \ninally the ex-pirate had enough of it. ",
	"Why don’t pirate marriages last much?\nBecause of all the arrrrguments.",
	"Wooden pegs and hooks are really expensive these days. \nThey cost an arm and a leg.",
	"What is a pirate’s favorite letter?\nP. because it would be an R, but it’s missing a leg.",
	"How can you tell a pirate has fallen for modern technology?\nIt’s the iPatch that gives it away.",
	"Why do pirates make great lawyers?\necause they have very good arrrrguments.",
	"Why is it so hard for pirates to learn to read?\nBecause they spend months and months at C.",
}
